\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename ../publish/blog/friends.info
@settitle Amigos
@documentencoding UTF-8
@documentlanguage es
@c %**end of header

@finalout
@titlepage
@title Amigos
@subtitle bing bing bang
@author Galindo
@end titlepage

@ifnottex
@node Top
@top Amigos
@end ifnottex

@menu
* misswannabe::
* vinizinho::
* jorgepinto::
* utsushimi::
* drawnbykalie::
* jamep-site::
@end menu

@node misswannabe
@unnumbered misswannabe

@uref{https://misswannabe.neocities.org/, file:https://neocities.org/site@math{_screenshots}/39/74/misswannabe/index.html.540x405.jpg}

@node vinizinho
@unnumbered vinizinho

@uref{https://vinizinho.neocities.org/, file:https://neocities.org/site@math{_screenshots}/25/71/vinizinho/index.html.540x405.jpg}

@node jorgepinto
@unnumbered jorgepinto

@uref{https://jorgepinto.neocities.org/, file:https://neocities.org/site@math{_screenshots}/89/15/jorgepinto/index.html.540x405.jpg}

@node utsushimi
@unnumbered utsushimi

@uref{https://utsushimi.neocities.org/, file:https://neocities.org/site@math{_screenshots}/29/48/utsushimi/index.html.540x405.jpg}

@node drawnbykalie
@unnumbered drawnbykalie

@uref{https://drawnbykalie.neocities.org/, file:https://neocities.org/site@math{_screenshots}/20/34/drawnbykalie/index.html.540x405.jpg}

@node jamep-site
@unnumbered jamep-site

@uref{https://jamep-site.neocities.org/, file:https://neocities.org/site@math{_screenshots}/22/52/jamep-site/index.html.540x405.jpg}

@bye