
#+TITLE: Programación
#+DATE: [2021-08-08 dom]

#+INCLUDE: "../includes/settings.org" 
# dom 08 ago 2021 02:43:35

* Introducción
Sí ya tienes suficiente tiempo leyendo mis post deberías saber que mi pasatiempo número uno es programar, para estas fechas ya debería tener casi 5-6 años dedicándole mi vida a escribir código, siempre cuento esta historia cada vez que consocio a alguien nuevo así que voy a aprovechar el tiempo libre que me queda y voy a poner en código la historia de como empecé a programar.

* Minecraft, mod scripts y mi primer bug
Todo empezó con mi otro gran hobby... Minecraft (PE) En el año de 2012 ( o 2013? ) con la versión 0.7.x , en ese entonces existían algo llamado modscrips, eran pequeños programas en JavaScript que se podían utilizar para añadir cosas al juego cosas como: comida, crafteos, herramientas y los más ambiciosos añadían hasta mobs, un día por casualidad se me ocurrió la idea de hacer click en uno de esos misteriosos modscripts (sí mi memoria no me falla creo que era el mod de "elemental swords"), solo eran un montón de líneas de código repetido varias veces y yo con todo el intelecto y nivel de ingles que un niño de 11-12 años puede tener procedí a crear mi primer "mod" (básicamente un clon de elemental swords), todo bien por los primeros minutos todo estuvo bien, pero después mi "mod" dejo de funcionar, en ese entonces no lo sabía, pero me había topado con mi primer bug, mi sospecha es que puse alguna minúscula en donde no debía (típico, camelCase arruinando mi vida desde siempre).

* Eligiendo una carrera técnica
Después de ese primer desencanto con la programación seguí con mi vida viviendo todas las aventuras que un mocoso de 11-12 años puede tener. Pase la primaria, la secundaria, y había llegado ese momento tenía que elegir cuál carrera técnica cursaría (ya tenía como 14 años) iba a tomar, mi hermana había ido en programación y pues como a mí me interesaban las computadoras se me ocurrió la idea de hacer exactamente lo mismo, así que eso hice. Cabe destacar que para cuando yo termine la secundaria mi sueño era ser historiador (más adelante explico como termine en ingeniería)

* Mi primera laptop, BATCH y C++
Bueno como regalo para mi cumpleaños número 15 mi mamá me regalo el dinero que me hacía falta para comprar mi primera laptop (la cual por cierto es la que sigo usando a diario) y mi viaje empezó... 
Durante mis primeros meses en la preparatoria nos enseñaron de la existencia del CMD, solo nos lo comentaron brevemente, pero yo por curiosidad empecé a jugar con los comandos y me volví bastante bueno programando en bash, incluso hice un programa que eliminaba un virus que ocultaba carpetas, tiempo después mi hermana me platico de una herramienta que habían usado "app-inventor", también aprendí a usarla. Los últimos meses de mi primer semestre pensando cual sería mi primer lenguaje, pensé en java y Python, pero por casualidades de la vida me encontré con los vídeos de programación en C++ de "Programación ATS". 

Me gustaría desviarme del tema un momento para hablar de lo importante que es Alejandro Miguel Taboada Sánchez (programación ATS) en mi vida y en mi desarrollo como programador, sí no hubiera sido por sus tutórales yo no estaría haciendo lo que hago ahora, básicamente sus vídeos cambiaron completamente todos los planes que yo tenía para mi futuro y no me hubiera podido dedicarme a lo que mas me gusta. 

Desafortunadamente el día 2 de agosto del 2019 falleció debido a un cáncer de rodilla que le habían diagnosticado tiempo atrás, aun así lo recuerdo con mucho cariño a pesar de que nunca le hable... Realmente cuando publicas algo no sabes la cantidad de personas a las que puedes influenciar. "Si puedes imaginarlo, puedes programarlo".

Y así concluye mi primer semestre en preparatoria.

* Mis primeros juegos 
Durante mi primer año también empecé a hacer juegos en C++, mi primer videojuego lo titulé "keywar". Básicamente una palabra iba cayendo desde la parte superior de la pantalla hasta la parte de abajo y tenías que escribirlas lo más rápido posible, el juego terminaba si varias palabras tocaban la parte inferior de la pantalla. Todo un éxito durante la feria de ciencias de ese año, todavía tengo las fotos.

* Final
Podría extenderme más sobre como aprendí programación web, php, cobol, assembly, lua etc.. Pero la verdad siento que no aporta nada a este relato que les acabo de contar para cuando entre a mi segundo año yo ya sabia que mi nueva meta era estudiar ingeniería. Siempre me da un poco de nostalgia recordar como empecé con esto, como unos vídeos de YouTube cambiaron por completo mis aspiraciones académicas y todas las cosas que he hecho hasta ahora. Se suponía que esta seria una pequeña entrada de mi blog y ya tengo varias horas escribiendo, hoy me sentía con muchas ganas de escribir y recordar todas las cosas que me llevaron a aquí... quizá me siento así porque hoy es mi último día de vacaciones o quizá simplemente es porque no quiero limpiar mi cuarto, no lo sé, pero hasta entonces me despido.

* Anexo
[2021-08-10 mar]
# mar 10 ago 2021 12:46:43

Encontré uno de mis [[./resources/4-El juego de la vida.txt][primeros códigos]], jajaja está horrible ya no programo así ¡lo juro!.
