
#+SETUPFILE: ~/.emacs.d/templates/html-level-1.org
#+EXPORT_FILE_NAME: ../publish/apuntes/calculo-multivariable.html
#+OPTIONS: num:t
#+HTML_CONTAINER: div


#+TITLE:    Cálculo Multivariable
#+SUBTITLE: Apuntes
#+DATE:     [2021-08-06 vie]

#+TOC: headlines 1

* Funciones discontinuas más comunes
Funciones Discontinuas Más Comunes:
- Un numero dividido entre 0 es indefinido, por lo tanto una función dividida entre 0 también es indefinida y por lo tanto discontinua.

- A los números negativos no le podemos sacar raíz cuadrada en el dominio de los números reales.

- Tangente, en los puntos \( \frac{(2k + 1)\pi}{2} \).

- Secante, en los puntos \( \frac{(2k + 1)\pi}{2} \).

- Cosecante, en los puntos \(\pi k\).

- logartimo de 10 en \( x \leq 0  \)

* Alcance de la funcion
** Dominio de una función
El dominio son los valores de X que puede tomar una función:

#+BEGIN_DEMONSTRATION
\[ f \begin{pmatrix} x \\ y \end{pmatrix} \ = \frac{ \sqrt{x+y+1} }{x - 1} \]
#+END_DEMONSTRATION

 La primera cosa que debemos tomar en cuenta en que puntos la función es discontinua, en este caso la función tiene dos discontinuidades, en el numerador y en el denominador. 

En el denominador no puede haber un número cero, entonces solo basta con resolver la ecuación \( x-1 = 0 \) para encontrar la discontinuidad. \( x = 1 \)

Como los números negativos no tienen raíces, no hay números reales que multiplicados sean negativos, se puede inferir que la función no existe en ningún punto que donde \( x+y+1 < 0 \).

Entonces, con la información que ya conocemos podemos decir que la función existe en todos los puntos donde \(x+y+1\) sea mayor a 0 y donde X sea diferente de 0. En notación matemática el dominio se escribiría así:

#+BEGIN_DEMONSTRATION
\[ \begin{Bmatrix}
  \begin{pmatrix} 
  x \\ y \\ 
  \end{pmatrix} \in \mathbb R^2: 
  x + y + 1 \geq 0 \wedge x \not = 1
\end{Bmatrix}  \]
#+END_DEMONSTRATION

[[https://youtu.be/qDr0R7hIjts][Video]]

** Imagen de una función (Rango)
El rango o imagen de una función es todo valor de Y que puede tomar nuestra función \( f: \mathbb R^n \to \mathbb R^m \):

- Sí la función a la cual queremos calcular su rango solo tiene un parámetro, significa que nos encontramos con una función vectorial \(n = 1\).


- Por otro lado sí la función acepta dos parámetros y retorna un tercero entonces estamos ante una superficie. \( n = 2 \) y \(m = 3\).

#+BEGIN_DEMONSTRATION
\[ f \begin{pmatrix} x \\ y \end{pmatrix} = \sqrt{9-x^2-y^2} \]
#+END_DEMONSTRATION

Para encontrar el rango es muy recomendable encontrar primero el [[Dominio de una función][dominio]] de la función, así podemos saber donde debemos empezar a evaluar, para nuestro ejemplo el dominio de la función es \( { (^x_y) \in \mathbb R^2: x^2 + y^2 \leq 9 } \).

La primera cosa que podemos notar en la función es que es una raíz, eso significa que no puede ser un valor negativo, por lo tanto el valor mas pequeño al que podemos calcular la raíz en el dominio de los reales es el número 0, este sería el valor mínimo de la imagen.

También podemos notar que los valores están elevados al cuadrado (los valores de X^2 y y^2 siempre son positivos) entonces sus valores siempre se le restan a 9 y entonces como siempre se van a restar los valores, podemos inferir que el valor más alto que puede retornar esta función es \(\sqrt{9} \), este sería el valor máximo de la imagen. 

El resultado que obtenemos es que el dominio de la función se extiende continuamente desde \( [0, 3] \).

[[https://youtu.be/qDr0R7hIjts][Video]]

* Plano

# En progreso 
# https://youtu.be/8bhelXiPWew
# https://youtu.be/KrPYYW_504U
# https://app.diagrams.net
# https://youtu.be/IddgDEBUsHs
# https://www.youtube.com/watch?v=qEVrSjLyOdU
# http://es.onlinemschool.com/math/assistance/cartesian_coordinate/plane_angl/


** Representación del plano 
un plano es un objeto ideal que solo posee dos dimensiones, y contiene infinitos puntos y rectas; es un concepto fundamental de la geometría junto con el punto y la recta. Su ecuacion es la siguiente:

#+BEGIN_DEMONSTRATION
\[
ax + by + cz + d = 0
\]
#+END_DEMONSTRATION

otras formas de representar el plano también podrian ser las siguiente:

** Ecuación vectorial del plano
#+BEGIN_DEMONSTRATION
\[
\boldsymbol{a} \cdot \boldsymbol{r} = \boldsymbol{n} \cdot \boldsymbol{r}_0
\]
#+END_DEMONSTRATION

** Ecuación escalar
#+BEGIN_DEMONSTRATION
\[
a (x-x_0) + b (y - y_0) + c (z - z_0) = 0
\]
#+END_DEMONSTRATION

* Ejercicios con planos
** Plano Entre Tres Puntos
Para determinar la funcion que se forma con tres punttos en el espacio, sustituimos los valores y calculamos el determinante de la matriz resultante:

#+BEGIN_DEMONSTRATION
\[ \begin{pmatrix}
   x-a_x   & y-a_y   & z-a_z   \\
   b_x-a_x & b_y-a_y & b_z-a_z \\
   c_x-a_x & c_y-a_y & c_x-a_z \\
\end{pmatrix} \]
#+END_DEMONSTRATION

[[https://github.com/Galindo-lab/calculator/blob/main/eigenmath/plano-entre-3-puntos][eigenmath]] | [[https://github.com/Galindo-lab/calculator/blob/main/xcas/plano.cas][KhiCas]] 

** Ángulo Entre Planos
para calcular el angulo entre dos planos usamos la siguiente ecuacion:

#+BEGIN_DEMONSTRATION
\[
\cos \theta = \frac{\vec{u} \cdot \vec{v}}{\left|\vec{u}\right|\left|\vec{v}\right|}
\]
#+END_DEMONSTRATION

donde n es un punto en \( \mathbb{R}^3 \), primero determinamos el valor absoluto de la normal de \(n_1\) y de \(n_2\) y los multiplicamos, ese sera nuestro divisor; Para el denominador calculamos el producto cruz entre \(n_1\) y \(n_2\) y obtenemos su valor de la normal; Y por ultimo calculamos el arcocoseno (\(cos^{-1}(\theta)\)) de nuestra divicion, ojo que el resultado esta en radianes.

[[https://github.com/Galindo-lab/calculator/blob/main/eigenmath/angulo-entre-dos-planos][eigenmath]] | [[https://youtu.be/qEVrSjLyOdU][Video]]

[fn:normal] formula de la normal \( \sqrt{ x^2 + y^2 + z^2 } \)

** Plano que pasa por un punto y es perpendicular a otro plano
Para encontrar un plano perpendicular podemos aplicar una de las operaciones de vectores el producto cruz, pero primero tendremos que encontrar el [[Vector de una recta o función][vector de la función]]. Y ya con el vector solo tenemos que encontrar el vector perpendicular (producto cruz) y pasamos los valores a la ecuacion [[Ecuación escalar][escalar del plano]]:

#+BEGIN_DEMONSTRATION
Punto por el que queremos que pasase la función:
\[
A = (2,3,4)
\]

Función y su forma de vector:
\[ 
3x+2y+z-6=0 \rightarrow B = (3,2,1)
\]

producto cruz (C):
\[
Det \begin{vmatrix}
x & y & z\\
3 & 2 & 1\\
2 & 3 & 4
\end{vmatrix} = (5, -10, 5)
\]

por ultimo sustituimos en la ecuacion del plano:
\[
(5)(x-2)+(-10)(y-3)+(5)(z-4) = 0
\]

\[
5x-10y+5z = 20+10-30 
\]

\[
\boxed{5x-10y+5z = 0}
\]

#+END_DEMONSTRATION

[[https://www.youtube.com/watch?v=RkMxfogdWJ0][Video]] 

* Rectas 
** Vector de una recta o función 
Para obtener el vector de una función simplemente extraemos los valores escalares que están multiplicando a nuestros valores coordenados:

#+BEGIN_DEMONSTRATION
función:
\[ \frac{1}{2} x + 7y - 4z - 6 = 0 \]

su vector:
\[ (\frac{1}{2}, 7, -4) \]

#+END_DEMONSTRATION

** Parametrizacion de una recta con dos puntos
Sustituimos los valores en la siguiente formula, P_1 es el punto de origen, P_2 punto final y t es un valor entre 0 y 1

#+BEGIN_DEMONSTRATION
\[
P_1 + t \cdot (P_2 - P_1)
\]
#+END_DEMONSTRATION

[[../calculadoras/calculo-recta.html][Calculadora]]

** Ecuación paramétrica de la recta a una ecuación simétrica
La ecuacion siemetrica de la recta nos permite encontrar la ecuacion continua de la recta[fn:ecuacion-continua-recta] simplemente resolviendo la ecuacion en los terminos que necesitemos. 

#+BEGIN_DEMONSTRATION
\[
L: \frac{x-x_0}{a_1} = \frac{y-y_0}{a_2} = \frac{z-z_0}{a_3}
\]
#+END_DEMONSTRATION

Para calculara simplemente tenemos que sustituir nuesto punto de paso \(P_0\) y nuestro vector de dirección \(\vec{a}\) en los valores en la formula:

#+BEGIN_DEMONSTRATION
Identificamos nuestro punto de paso y nuestro vector de dirección:

\[
\Bigg\{ \begin{aligned}
     x &= -4 + 2t\\
     y &= -2  \\
     z &= -2 +5t
\end{aligned} 
\]

punto de paso \( P_0 = (-4,-2,-2) \).
vector de dirección \( \vec{a} = (2,0,5) \).

ahora sustituimos:

\[
L: \frac{x-4}{2} = \frac{y-2}{0} = \frac{z-2}{5}
\]

Cuando nos quede 0 en el denominador de alguna ecuación simplemente sustituimos el valor por su igualación a 0:

\[
L: \frac{x-4}{2} = \frac{z-2}{5} \land y = -2
\]

#+END_DEMONSTRATION

[[https://youtu.be/JMVEYTqdh6c][Video]]

[fn:ecuacion-continua-recta] 
\[ \frac{x-x_1}{v_1} = \frac{y-y_1}{v_2} \]


