
#+SETUPFILE: ~/.emacs.d/templates/html-level-1.org
#+EXPORT_FILE_NAME: ../publish/apuntes/ecuaciones-diferenciales.html
#+OPTIONS: num:t

#+TITLE:    Ecuaciones Diferenciales
#+SUBTITLE: Apuntes
#+DATE:     [2021-08-19 jue]

#+TOC: headlines 2

* Definicion
Una ecuacion diferencial, es una ecuacion donde la incognita es una funcion y que contiene una derivada de una o mas variables dependientes con respecto a dos o mas variables independientementes.

* Variables dependientes e independientes 
- Variable dependiente :: Es aquella cuyos valores dependen de los que tomen otra variable. Usualmente se suele representar como *y* en el eje de las ordenadas.

- Variable independiente :: Un símbolo que representa una entrada de datos arbitraria se denomina variable independiente,

#+BEGIN_DEMONSTRATION
En esta ecuacion diferencial podemos saber cual es la variable independiente con solo mirar el denominador, en este caso \(x\), entonces como \(x\) es independiente \(y\) es la variable independiente[fn:nota-notacion].

\[\frac{dy}{dx} = 0.2 \cdot x \cdot y\]

#+END_DEMONSTRATION

[[https://es.wikipedia.org/wiki/Variables_dependientes_e_independientes][Más informacion]]

[fn:nota-notacion] recuerda que \( \frac{dy}{dx} = y' \).

* Orden de una ecuacion
Se dice que una ecuacion es del grado de su derivada mas alta[fn:nota-exp]

#+BEGIN_DEMONSTRATION
Ecuaciones de primer orden: 

\[\frac{dy}{dx} = \frac{1}{2} xy \]

\[(y')^2 + xy'-y = 0 \]

#+END_DEMONSTRATION

Mientras mas comillas tiene una derivada eso significa que es de mayor grado:

#+BEGIN_DEMONSTRATION

Ecuaciones de segundo orden:

\[y'' + a(x)y' + b(x)y = f(x)  \]

\[y'' + \frac{a(x)}{a_0(x)}) y' + \frac{b(y)}{a_0(x)}y = 0  \]

#+END_DEMONSTRATION

[fn:nota-exp] Ojo, el exponente en la ecuacion no afecta el grado de la derivada.

* Campos de pendientes o direcciones
Un campo de pendientes es un tipo de grafico que funciona como una solucion grafica para ecuaciones diferenciales de primer orden. \\
Para dibujar un campo de pendientes solo tenemos que evaluar la funcion en cada punto, Sí el numero resultante es positivo dibujamos una linea en diagonal hacia abajo ⟍ pero sí la linea es negativa dibujamos una lina diagonal hacia arriba ⟋.

[[https://youtu.be/xu_HLUShvws][Video]] | [[https://www.geogebra.org/m/R36YDrma][Graficador]]

* Transformada de Laplace
En matemáticas, la transformada de Laplace es una transformada integral que convierte una función de variable real {\displaystyle t}t (normalmente el tiempo) a una función de variable compleja {\displaystyle s}s. Tiene muchas aplicaciones en ciencia e ingeniería porque es una herramienta para resolver ecuaciones diferenciales. En particular, transforma ecuaciones diferenciales en ecuaciones algebraicas.

Para resolver una transformada de laplace susituimos \(f(t)\) con nuestra funcion en base a t:

\[ 
L \{f(t)\} = \int_0^\infty e^{-s~t} f(t)~dt
\] 

[[https://es.wikipedia.org/wiki/Transformada_de_Laplace][Fuente]] | [[https://www.mediafire.com/file/p332e66d6vmdic8/laplace.pdf/file][Formulario]]

* Aplicaciones de transformada de laplace
Raramente te van a pedir que desarolloes las integrales para llegar a una transformada, por lo general simplemente usamos sus aplicaciones, las aplicaciones de tranformada de Laplace simplemente son sustituciones de funciones comunes, En el [[https://www.mediafire.com/file/p332e66d6vmdic8/laplace.pdf/file][formulario]] puedes encontrar la mayoria de sustituciones.

#+BEGIN_DEMONSTRATION

\[ \begin{aligned}
                 f(t) &= 2t^4 \\
\mathcal{L}\{ f(t) \} &= 2\mathcal{L}\{ t^4 \}\\
                      &= 2 \frac{4!}{s^{4+1}}\\
                      &= \frac{24}{s^{5}}
\end{aligned} \]

\[ 
\boxed{\mathcal{L}\{ f(t) \} = \frac{24}{s^{5}}}
\]
#+END_DEMONSTRATION

Como se ve en el ejemplo, simplemente tenemos que desarollar la exprecion y aplicar la [[https://www.mediafire.com/file/p332e66d6vmdic8/laplace.pdf/file][formula]] que se nos indica.

# ** Integral Propia 
