
#+SETUPFILE: ~/.emacs.d/templates/html-level-1.org
#+EXPORT_FILE_NAME: ../publish/apuntes/matematicas-discretas.html
#+OPTIONS: num:t

#+TITLE:    Matemáticas Discretas
#+SUBTITLE: Apuntes
#+DATE:     [2021-08-10 mar]

#+TOC: headlines 1

* Lenguaje formal
El lenguaje formal es un lenguaje artificial, convencional, elegido de manera consciente y cuidadosa para expresarse precisa,
sistemática, rigurosa y unívocamente, por lo común dentro de
un cierto campo del saber y con determinados fines.

* Lenguaje natural
El lenguaje natural es aquel que utilizamos cotidianamente. Surge históricamente dentro de la sociedad y es aprendido sin que
exista necesariamente en el individuo un acto reflexivo.

* Variables proposiciones 
conjunto de _enunciados declarativos_ que formalizan la expresión, usualmente se les denota con las letras (p, q, r, s...).

+ Enunciado declarativo :: es aquella proposición de lenguaje objeto de la caal podemos predicar su verdad o su falsedad.

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER
/"Hay un automóvil blanco en el aparcamento"/.
#+END_CENTER
#+END_DEMONSTRATION

+ Enunciado NO declarativo :: es un enunciado que no puede ser convertido a lenguaje formal.

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER
/"¿Dónde esta mi automóvil?"/. \\
/"¡Guarda silencio!"/. \\
#+END_CENTER
#+END_DEMONSTRATION

+ Enunciado atómico :: es aquél enunciado único, que en su expresión no incluye ningún conectivo lógico, es decir, no une dos o más enunciados.
     
#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER
/"Hoy es miércoles."/ \\
/"Vivo en el distrito Federeal."/ \\
/"Pablo es matematico"/ \\
#+END_CENTER
#+END_DEMONSTRATION 

[[http://objetos.unam.mx/logica/formasLogicas/pdf/forma.logica.de.enunciados.pdf][Extraido]] 

* Conectivas proposicionales
son los simbolos que formalizan los elementos del lenguaje que sirven para su funcion argumentativa.

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER
#+ATTR_HTML: :align center :rules all :border 1 :frame 1 :mode inline-math
| Relacion        | Notación     | Lectura              |
| <15>            | <12>         | <20>                 |
|-----------------+--------------+----------------------|
| Negacion        | \(\lnot\)    | no                   |
| Conjunción      | \(\lor   \)  | o                    |
| Disyunción      | \(\land\)    | y[fn:tip-and]        |
| Implicación     | \(\rightarrow\) | entonces             |
| Equivalencia    | \(\equiv  \) | equivalente a        |
| Por lo tanto    | \(\vdash\)   | deduce que, conclusion |
#+END_CENTER
#+END_DEMONSTRATION

[[https://en.wikipedia.org/wiki/List_of_logic_symbols][Lista de simbolos completa]] \\

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER

p \equiv "Hago ejercicio diariamente." \\
q \equiv "Me alimento sanamente." \\
r \equiv "Tengo buena salud." \\

/"Hago ejercicio diariamente y me alimento sanamente"/ \\

\( p \land q \)

/"No tengo buena salud y no hago ejercicio  diariamente"/ \\

\( ¬r \land ¬p \)

/"Si me alimento sanamente y hago ejercicio diariamente, entonces tengo buena salud"/ \\

\( (p \land q) \implies r \)

#+END_CENTER
#+END_DEMONSTRATION

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER

p \equiv "Viene Julia" \\
q \equiv "Viene María" \\
r \equiv "Viene Javier" \\

/"Viene Julia, María y Javier"/ \\

\( p \land q \land r \)

#+END_CENTER
#+END_DEMONSTRATION

[fn:tip-and] Una forma para identificar cual simbolo es "y" es recordar que ambas tienen forma de "v", osea ambas apuntan hacia abajo.

* Tautología
es un forma de enunciado que siempre es verdadera, independientemente de los valores de verdad de los enunciados individuales sustituidos por sus enunciados variables. Un enunciado cuya forma es una tautología es un *enunciado tautológico*.

* Contradicción
es una forma de enunciado que siempre es falso, independientemente de los valors de verdad de los enunciados individuales de los enunciados sustituidos. Un enunciado cuya forma es una contradicción es un *enunciado contradictorio*.

* Tablas de verdad
Son tablas que nos sirven para conocer los valores de verdad de las proposiciones compuestas.

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER

 p \equiv /"salió electo Presidente de la República"/ \\
 q \equiv /"el crecimiento anual fue del 7%"/ \\

 /"No salió electo Presidente de la República o el crecimiento anual no fue del 7%"/ \\

#+ATTR_HTML: :align center :rules all :border 1 :frame 1 :mode inline-math
|---+---+----+----+-----+------+------+-------|
| p | q | ¬p | ¬q | p∧q | ¬p∧q | p∧¬q | ¬p∧¬q |
|---+---+----+----+-----+------+------+-------|
| F | F | V  | V  | F   | V    | V    | V     |
|---+---+----+----+-----+------+------+-------|
#+END_CENTER
#+END_DEMONSTRATION

[[https://calculadorasonline.com/generador-de-tablas-de-verdad-logica-proposicional-algebra-booleana/][Generador de tablas de verdad]] 

* Equivalencia lógica
Dos formas de enunciado se llaman lógicamente equivalents si y sólo si, tienen los mismos valores de verdad para cada posible sustitución de enunciados por sus enunciados de variables. La equivalencia lógica de las formas de enunciado P y Q se denota escribiendo P ≡ Q.

* Leyes commutativas
Establecen que el orden en el cual sume o multiplique dos números reales no afecta el resultado.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
 p \land q &\equiv q \land p &
 p \lor q &\equiv q \lor p
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes asociativas 
Establecen que cuando suma o multiplica cualesquiera tres números reales, el grupo (o asociación) de los números no afecta el resultado.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
 (p \land q) \land r &\equiv p \land (q \land r) \\
 (p \lor q) \lor r &\equiv p \lor (q \lor r)
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes distributivas
Expresa que se obtiene la misma respuesta cuando multiplicas un conjunto de números por otro número que cuando se hace cada multiplicación por separado

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
 p \land (q \lor r) &\equiv (p \land q) \lor (p \land r) \\
 p \lor (q \land r) &\equiv (p \lor q) \land (p \lor r)
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes de la identidad
Es la constatación de que dos objetos que matemáticamente se escriben diferente, son de hecho el mismo objeto.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
 p \land t &\equiv p &
 p \lor c &\equiv p
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes de negacion
Dada una proposición p su contraria no p es verdadera.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
p \land \lnot p &\equiv t & p \lor \lnot p &\equiv c
\end{aligned} \]
#+END_DEMONSTRATION

* Ley de la doble negacion
se produce cuando se combina el adverbio no con la presencia de otros elementos que tienen también sentido negativo.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
\lnot(\lnot p) \equiv p
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes de idempotencia
es la propiedad para realizar una acción determinada varias veces y aun así conseguir el mismo resultado que se obtendría si se realizase una sola vez.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
p \land p &\equiv p & p \lor p &\equiv p 
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes universales acortadas

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
p \lor t &\equiv t & p \land c &\equiv c
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes de morgan
son un par de reglas de transformación que son ambas reglas de inferencia válidas. Las normas permiten la expresión de las conjunciones y disyunciones puramente en términos de vía negación.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
\lnot ( p \land q ) &\equiv \lnot p \lor \lnot q & 
\lnot ( p \lor q ) &\equiv \lnot p \land \lnot q
\end{aligned} \]
#+END_DEMONSTRATION

* Leyes de absorción

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
p \lor (p \land q) &\equiv p & p \land (p \lor q) &\equiv p
\end{aligned} \]
#+END_DEMONSTRATION

* Negaciones de *t* y *c*
El negativo de una tautología es una contradicción y el opuesto de una contradicción es una tautología.

#+BEGIN_DEMONSTRATION
\[ \begin{aligned}
\lnot t &\equiv c & \lnot c &\equiv t
\end{aligned} \]
#+END_DEMONSTRATION
* Implicación
La implicación logica se emplea para representar una afirmacion no hipotetica, es decir: A es verdadero por lo tanto B es verdadero.

#+BEGIN_DEMONSTRATION
#+BEGIN_CENTER

"Sí llueve, el suelo esta mojado" \\
"llueve. por tanto, el suelo esta mojado"\\

#+END_CENTER
#+END_DEMONSTRATION

* Validación de argumentos (Demostración)
Un argumento es valido (lógico) sí la conclusion  es verdadera siempre y cuando todas las premisas sean verdaderas

#+BEGIN_DEMONSTRATION
Un argumento valido seria algo como: \\

\[ ((\lnot p \implies q) \land (p \implies (\lnot r \lor s))) \implies ( \lnot s \land \lnot q \land \lnot r ) \implies p\]

#+END_DEMONSTRATION
