
#+SETUPFILE: ~/.emacs.d/templates/html-level-1.org
#+EXPORT_FILE_NAME: ../publish/emacs/blog-en-org-mode.org


#+TITLE:    Blog con ORG-mode
#+SUBTITLE: Emacs
#+DATE:     [2021-08-04 mié]

* Introducción 
Org mode es sin ninguna duda una de las "killer features" de emacs, permite hacer básicamente todas mis labores relacionadas con hacer notas, pero hoy no estoy aquí para hablar de las bondades de ORG-mode, Voy a explicarte como hacer tu propio blog con paginas estáticas con org mode. 

* Opciones Para Org 
Mi configuración para mis archivos de org es muy breve:

#+BEGIN_SRC
#+OPTIONS: html-style:nil html-scripts:nil num:nil html-postamble:nil
#+END_SRC

+ html-style :: desactiva todo el css generado por org mode, de todos modos prefiero hacer mis propias hojas de estilo.
+ html-scripts :: con esta opción desactivo el javascript generado por ORG-mode.
+ num :: los números en los títulos.
+ html-postamble :: el postamble es texto que se añade al final de cada documento yo prefiero desactivarlo.

* HTML HEAD
HTML HEAD nos permite insertar html en la sección head del css generado por ORG:

#+BEGIN_SRC
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+END_SRC

siempre ajusto el viewport de la pagina para que sea mas fácil de ver en los móviles, en la segunda linea estamos incluyendo el css personalizado de nuestro sitio.

* Insertar seccion en html
Para insertar un div con un nombre de clase personalizado simplemente tenemos que insertar un bloque de código con el nombre que deseamos poner a nuestro bloque:

#+BEGIN_SRC 
#+BEGIN_juan

#+END_juan
#+END_SRC

* Conclusión
Como vez es muy fácil hace sitios web en Org-mode, en esta entrada yo no explique ni la mitad de las cosas que puede hacer ORG-mode, pero con la información anterior ya deberías poder hacer un sitio a tu gusto sin tener que preocuparte por los defaults de ORG.
